# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
primary_default: &primary_default
  adapter: postgresql
  timeout: 5000

crawler_default: &crawler_default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  host: <%= ENV['CRAWLER_DB_HOST'] %>
  username: <%= ENV['CRAWLER_DB_USERNAME'] %>
  password: <%= ENV['CRAWLER_DB_PASSWORD'] %>
  database: mc_crawler_v2
  migrations_paths: db/crawler_migrate
  timeout: 5000

crawler_replica_default: &crawler_replica_default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  host: <%= ENV['CRAWLER_REPLICA_DB_HOST'] %>
  username: <%= ENV['CRAWLER_DB_USERNAME'] %>
  password: <%= ENV['CRAWLER_DB_PASSWORD'] %>
  database: mc_crawler_v2
  migrations_paths: db/crawler_migrate
  timeout: 5000
  replica: true

development:
  primary:
    <<: *primary_default
    database: matchcasts_acl_development
    # database: matchcasts_acl_staging
    # host: <%= ENV['APP_DB_HOST'] %>
    # username: <%= ENV['APP_DB_USERNAME'] %>
    # password: <%= ENV['APP_DB_PASSWORD'] %>
  crawler:
    <<: *crawler_default
  crawler_replica:
    <<: *crawler_replica_default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *primary_default
    database: matchcasts_acl_test
  crawler:
    <<: *crawler_default
  crawler_replica:
    <<: *crawler_replica_default

staging:
  primary:
    <<: *primary_default
    database: matchcasts_acl_staging
    host: <%= ENV['APP_DB_HOST'] %>
    username: <%= ENV['APP_DB_USERNAME'] %>
    password: <%= ENV['APP_DB_PASSWORD'] %>
  crawler:
    <<: *crawler_default
  crawler_replica:
    <<: *crawler_replica_default

production:
  primary:
    <<: *primary_default
    database: matchcasts_acl_production
    host: <%= ENV['APP_DB_HOST'] %>
    username: <%= ENV['APP_DB_USERNAME'] %>
    password: <%= ENV['APP_DB_PASSWORD'] %>
  crawler:
    <<: *crawler_default
  crawler_replica:
    <<: *crawler_replica_default
